# Generated by Django 4.0.1 on 2022-01-16 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankAccounts', '0003_alter_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('third_party_api', models.CharField(blank=True, choices=[('1', 'default')], default='1', max_length=20)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_transactions', to='bankAccounts.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_transactions', to='bankAccounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
