# Generated by Django 4.0.1 on 2022-01-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankAccounts', '0006_transaction_balance_transaction_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='from_account_id',
            new_name='from_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_account_id',
            new_name='to_account',
        ),
    ]
