# Generated by Django 4.0.1 on 2022-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankAccounts', '0007_rename_from_account_id_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='third_party_api',
            field=models.CharField(blank=True, choices=[('1', 'exchangeratesapi.io')], default='1', max_length=20),
        ),
    ]
