version: "3.7"

services:
  redis:
    image: redis:latest
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    volumes:
      - ./accountManagementService:/opt
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      /bin/bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
  #TODO: Add nginx and gunicorn