version: "3.7"

services:
  redis:
    image: redis:latest
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    volumes:
      - ./accountManagementService:/opt
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXCHANGE_API_ACCESS_KEY=b6642a60eab8049e55806d8ac18e6b57 # TODO: secret this access key
      - EXCHANGE_API_CACHE_SECONDS=36000 # TODO: change it into 1 seconds
      - STATIC_ROOT=/opt/static
    depends_on:
      - db
      - redis
    command: >
      /bin/bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
  #TODO: Add nginx and gunicorn